export {default as login} from './login'
export {default as register} from './register'
export {default as auth} from './auth'
export {default as emailVerification} from './emailVerification'
export {default as sendCodeToEmail} from './sendCodeToEmail'